/**
 * Manifiesto de las 60 imagenes reales usadas por el seed de reportes
 * ciudadanos sinteticos (Acuifero Patino). Usado por
 * prisma/download-seed-images.ts para descargar/verificar los archivos, y
 * como fuente de la trazabilidad documentada en
 * docs/seed-reportes-imagenes.md.
 *
 * Todas las imagenes provienen de Wikimedia Commons, Unsplash o Pexels, con
 * licencia libre o de dominio publico. Fecha de consulta: 2026-07-28.
 */

const FECHA_CONSULTA = '2026-07-28';

const IMAGENES = [
  // ---- Reporte 01 (Villeta A, RIESGO_ALTO) ----
  { archivo: 'reporte-01-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Oil_sheen_on_pond.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Oil_sheen_on_pond.jpg', sitio: 'Wikimedia Commons', autor: 'Jomegat', licencia: 'CC BY-SA 3.0', categoria: 'capa aceitosa', descripcion: 'Pelicula aceitosa con colores iridiscentes sobre la superficie de un estanque, New Hampshire.' },
  { archivo: 'reporte-01-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/0/03/OIL_SLUDGE_FLOATS_ON_WATER_AT_YACHT_BASIN_-_NARA_-_552270.jpg', origen: 'https://commons.wikimedia.org/wiki/File:OIL_SLUDGE_FLOATS_ON_WATER_AT_YACHT_BASIN_-_NARA_-_552270.jpg', sitio: 'Wikimedia Commons', autor: 'Doug Wilson (EPA/Documerica, NARA)', licencia: 'Dominio publico (obra de un empleado federal de EE.UU.)', categoria: 'capa aceitosa', descripcion: 'Lodo aceitoso flotando sobre el agua en una darsena (fotografia historica, 1973).' },

  // ---- Reporte 02 (Villeta B, RIESGO_ALTO) ----
  { archivo: 'reporte-02-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/3/38/DIRTY%2C_OILY_WATER_OF_POND_BESIDE_AUTOMOBILE_SCRAP_YARD_-_NARA_-_554347.jpg', origen: 'https://commons.wikimedia.org/wiki/File:DIRTY,_OILY_WATER_OF_POND_BESIDE_AUTOMOBILE_SCRAP_YARD_-_NARA_-_554347.jpg', sitio: 'Wikimedia Commons', autor: 'Dan McCoy (EPA/Documerica, NARA)', licencia: 'Dominio publico', categoria: 'entorno industrial', descripcion: 'Estanque de agua sucia y aceitosa junto a un deposito de chatarra de automoviles, Jersey City (1973).' },
  { archivo: 'reporte-02-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/1/11/SCOTT_SULPHITE_PULP_MILL_DISCHARGES_WATER_WASTE_-_NARA_-_552152.jpg', origen: 'https://commons.wikimedia.org/wiki/File:SCOTT_SULPHITE_PULP_MILL_DISCHARGES_WATER_WASTE_-_NARA_-_552152.jpg', sitio: 'Wikimedia Commons', autor: 'Doug Wilson (EPA/Documerica, NARA)', licencia: 'Dominio publico', categoria: 'descarga industrial', descripcion: 'Descarga de residuo liquido de una planta de pulpa de papel hacia un curso de agua (1973).' },

  // ---- Reporte 03 (Ricardo Brugada A, RIESGO_ALTO) ----
  { archivo: 'reporte-03-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/6/68/GARBAGE_AND_TRASH_ALONG_BANK_OF_CHATTAHOOCHEE_RIVER_-_NARA_-_545945.jpg', origen: 'https://commons.wikimedia.org/wiki/File:GARBAGE_AND_TRASH_ALONG_BANK_OF_CHATTAHOOCHEE_RIVER_-_NARA_-_545945.jpg', sitio: 'Wikimedia Commons', autor: 'Chuck Rogers (EPA/Documerica, NARA)', licencia: 'Dominio publico', categoria: 'residuos en cauce', descripcion: 'Basura y desechos acumulados en la orilla del rio Chattahoochee, Atlanta (1972).' },
  { archivo: 'reporte-03-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/8/81/POLLUTED_WATER.jpg', origen: 'https://commons.wikimedia.org/wiki/File:POLLUTED_WATER.jpg', sitio: 'Wikimedia Commons', autor: 'Finn Terman Frederiksen', licencia: 'CC BY 2.0', categoria: 'descarga cloacal', descripcion: 'Escorrentia de agua residual/cloacal contaminando el entorno cercano.' },

  // ---- Reporte 04 (Ricardo Brugada B, RIESGO_ALTO) ----
  { archivo: 'reporte-04-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/f/f1/Rio_poluído_de_Mantena.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Rio_poluído_de_Mantena.jpg', sitio: 'Wikimedia Commons', autor: 'Josue200818', licencia: 'CC BY-SA 3.0', categoria: 'agua muy turbia', descripcion: 'Rio turbio y contaminado en Mantena, Minas Gerais, Brasil.' },
  { archivo: 'reporte-04-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/e/eb/Basura_en_Cochabamba_02.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Basura_en_Cochabamba_02.jpg', sitio: 'Wikimedia Commons', autor: 'Nachof08', licencia: 'CC BY-SA 4.0', categoria: 'canal/desague', descripcion: 'Canal de drenaje urbano con acumulacion de basura y agua de aspecto sucio, Cochabamba, Bolivia.' },

  // ---- Reporte 05 (Sajonia, RIESGO_ALTO) ----
  { archivo: 'reporte-05-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Water-pollution.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Water-pollution.jpg', sitio: 'Wikimedia Commons', autor: 'FatYellowFish', licencia: 'CC BY-SA 4.0', categoria: 'agua turbia/oscura', descripcion: 'Agua sucia con residuos flotando, coloracion oscura visible.' },
  { archivo: 'reporte-05-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/8/81/BOW_OF_FISHING_BOAT_IN_POLLUTED_HARBOR_-_NARA_-_545270.jpg', origen: 'https://commons.wikimedia.org/wiki/File:BOW_OF_FISHING_BOAT_IN_POLLUTED_HARBOR_-_NARA_-_545270.jpg', sitio: 'Wikimedia Commons', autor: 'Gene Daniels (EPA/Documerica, NARA)', licencia: 'Dominio publico', categoria: 'entorno industrial/portuario', descripcion: 'Proa de una embarcacion pesquera en un puerto con agua visiblemente contaminada (1972).' },

  // ---- Reporte 06 (Tacumbú, RIESGO_ALTO) ----
  { archivo: 'reporte-06-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/4/46/THESE_FISHING_BOATS_HAVE_PRODUCED_THE_OIL_SLICK_ON_WHICH_THEY_RIDE_-_NARA_-_542980.jpg', origen: 'https://commons.wikimedia.org/wiki/File:THESE_FISHING_BOATS_HAVE_PRODUCED_THE_OIL_SLICK_ON_WHICH_THEY_RIDE_-_NARA_-_542980.jpg', sitio: 'Wikimedia Commons', autor: 'Tomas Sennett (EPA/Documerica, NARA)', licencia: 'Dominio publico', categoria: 'capa aceitosa', descripcion: 'Embarcaciones pesqueras flotando sobre una mancha de hidrocarburo en el agua, California (1972).' },
  { archivo: 'reporte-06-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/c/ce/Half_sunk_bucket.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Half_sunk_bucket.jpg', sitio: 'Wikimedia Commons', autor: 'Saral Shots', licencia: 'CC BY-SA 4.0', categoria: 'residuos en cauce', descripcion: 'Balde semihundido en agua estancada, ejemplo de residuo abandonado en un cauce.' },

  // ---- Reporte 07 (San Lorenzo A, RIESGO_ALTO) ----
  { archivo: 'reporte-07-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/0/00/Muddy_USGS.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Muddy_USGS.jpg', sitio: 'Wikimedia Commons', autor: 'USGS (Office of Water Quality)', licencia: 'Dominio publico', categoria: 'agua muy turbia', descripcion: 'Curso de agua con color marron cargado de sedimento en suspension.' },
  { archivo: 'reporte-07-02.webp', url: 'https://images.unsplash.com/photo-1655365035125-e36d1379bf65', origen: 'https://unsplash.com/photos/a-boat-on-a-muddy-river-9eoWFr-0Mo0', sitio: 'Unsplash', autor: 'Leo_Visions', licencia: 'Unsplash License', categoria: 'agua muy turbia', descripcion: 'Orilla de un rio completamente turbio y de color marron, entorno selvatico.' },

  // ---- Reporte 08 (Ricardo Brugada C, RIESGO_MEDIO) ----
  { archivo: 'reporte-08-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Creek_Water_Pollution.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Creek_Water_Pollution.jpg', sitio: 'Wikimedia Commons', autor: 'Global Water Forum', licencia: 'CC BY 2.0', categoria: 'residuos plasticos', descripcion: 'Residuos plasticos obstruyendo un pequeno curso de agua.' },
  { archivo: 'reporte-08-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/b/b3/Eau_stagnante_a_Foto.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Eau_stagnante_a_Foto.jpg', sitio: 'Wikimedia Commons', autor: 'Tsopbeng vannelle', licencia: 'CC0 1.0', categoria: 'agua estancada', descripcion: 'Agua estancada de entorno residencial, propicia para la cria de mosquitos.' },

  // ---- Reporte 09 (San Lorenzo B, RIESGO_MEDIO) ----
  { archivo: 'reporte-09-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Algalbloom.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Algalbloom.jpg', sitio: 'Wikimedia Commons', autor: 'Koyaanis Qatsi', licencia: 'Dominio publico', categoria: 'algas', descripcion: 'Superficie de agua cubierta con floracion de algas y hojarasca.' },
  { archivo: 'reporte-09-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/5/57/171a_365_-_Green_Pond_%284985235160%29.jpg', origen: 'https://commons.wikimedia.org/wiki/File:171a_365_-_Green_Pond_(4985235160).jpg', sitio: 'Wikimedia Commons', autor: 'Derek Hatfield', licencia: 'CC BY 2.0', categoria: 'algas', descripcion: 'Pequeno arroyo cubierto casi en su totalidad por una capa verde de algas, Ontario.' },

  // ---- Reporte 10 (Villa Elisa, RIESGO_MEDIO) ----
  { archivo: 'reporte-10-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/b/b2/Algae_bloom_on_farm_pond._North_western_West_Virginia._2012_USEPA_photo_by_Eric_Vance_%2813765604433%29.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Algae_bloom_on_farm_pond._North_western_West_Virginia._2012_USEPA_photo_by_Eric_Vance_(13765604433).jpg', sitio: 'Wikimedia Commons', autor: 'Eric Vance (USEPA)', licencia: 'Dominio publico', categoria: 'algas', descripcion: 'Estanque de granja con una floracion de algas de color verde intenso.' },
  { archivo: 'reporte-10-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/b/b1/Laguna_Lake_Blue-Green_Algae_Bloom_%2848701932783%29.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Laguna_Lake_Blue-Green_Algae_Bloom_(48701932783).jpg', sitio: 'Wikimedia Commons', autor: 'Joyce Cory', licencia: 'CC BY 2.0', categoria: 'algas', descripcion: 'Floracion de cianobacterias verde-azuladas en un lago, Filipinas.' },

  // ---- Reporte 11 (Ñemby, RIESGO_MEDIO) ----
  { archivo: 'reporte-11-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/8/8c/Blocked_drainage_in_Morogbo_Badagry%2C_Lagos_State%2C_Nigeria.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Blocked_drainage_in_Morogbo_Badagry,_Lagos_State,_Nigeria.jpg', sitio: 'Wikimedia Commons', autor: 'Macdanpets', licencia: 'CC BY-SA 4.0', categoria: 'canal/desague', descripcion: 'Zanja de drenaje cubierta de maleza y agua estancada, Nigeria.' },
  { archivo: 'reporte-11-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/A_blocked_drainage_at_Morogbo.jpg', origen: 'https://commons.wikimedia.org/wiki/File:A_blocked_drainage_at_Morogbo.jpg', sitio: 'Wikimedia Commons', autor: 'Bibiire1', licencia: 'CC BY-SA 4.0', categoria: 'canal/desague', descripcion: 'Canal de drenaje bloqueado por acumulacion de residuos, agua de aspecto turbio, Nigeria.' },

  // ---- Reporte 12 (San Antonio, RIESGO_MEDIO) ----
  { archivo: 'reporte-12-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/e/e6/Runoffrazorback.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Runoffrazorback.jpg', sitio: 'Wikimedia Commons', autor: 'Anlace', licencia: 'Dominio publico', categoria: 'arrastre de sedimento', descripcion: 'Escorrentia superficial en una ladera con agua cargada de sedimento tras saturacion del suelo.' },
  { archivo: 'reporte-12-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/e/ea/Blocked_drainage_in_Mbare%2C_Harare_%286915329193%29.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Blocked_drainage_in_Mbare,_Harare_(6915329193).jpg', sitio: 'Wikimedia Commons', autor: 'SuSanA Secretariat', licencia: 'CC BY 2.0', categoria: 'canal/desague', descripcion: 'Drenaje pluvial bloqueado con residuos solidos, Harare, Zimbabue.' },

  // ---- Reporte 13 (Itauguá A, RIESGO_MEDIO) ----
  { archivo: 'reporte-13-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/5/59/Algae_bloom_in_Reflecting_Pool%2C_Washington%2C_DC._2007_Potomac_River%2C_Chesapeake_Bay_watershed._USEPA_photo_by_Eric_Vance_%2813765962984%29.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Algae_bloom_in_Reflecting_Pool,_Washington,_DC._2007_Potomac_River,_Chesapeake_Bay_watershed._USEPA_photo_by_Eric_Vance_(13765962984).jpg', sitio: 'Wikimedia Commons', autor: 'Eric Vance (USEPA)', licencia: 'Dominio publico', categoria: 'algas', descripcion: 'Espejo de agua urbano con coloracion verde por eutrofizacion, Washington DC.' },
  { archivo: 'reporte-13-02.webp', url: 'https://images.unsplash.com/photo-1549627813-3a2531e6af42', origen: 'https://unsplash.com/photos/green-color-water-gR_AgAcP7jI', sitio: 'Unsplash', autor: 'Mihály Köles', licencia: 'Unsplash License', categoria: 'algas', descripcion: 'Rio con una extensa floracion algal que cubre gran parte de la superficie de color verde.' },

  // ---- Reporte 14 (Itauguá B, RIESGO_MEDIO) ----
  { archivo: 'reporte-14-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/f/f2/Water_pollution_in_Nairobi.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Water_pollution_in_Nairobi.jpg', sitio: 'Wikimedia Commons', autor: 'Queen Asali', licencia: 'CC BY-SA 4.0', categoria: 'canal/desague', descripcion: 'Sistema de drenaje con agua de coloracion anaranjada y aspecto turbio, Nairobi.' },
  { archivo: 'reporte-14-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/d/d5/A_drainage_at_Ibereko%2C_Badagry%2C_Lagos_State%2C_Nigeria.jpg', origen: 'https://commons.wikimedia.org/wiki/File:A_drainage_at_Ibereko,_Badagry,_Lagos_State,_Nigeria.jpg', sitio: 'Wikimedia Commons', autor: 'Macdanpets', licencia: 'CC BY-SA 4.0', categoria: 'canal/desague', descripcion: 'Canal de drenaje urbano, Lagos, Nigeria.' },

  // ---- Reporte 15 (Luque, RIESGO_MEDIO) ----
  { archivo: 'reporte-15-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Stuffy_and_blocked_drainage_at_Agbara%2C_Badagry_Expressway.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Stuffy_and_blocked_drainage_at_Agbara,_Badagry_Expressway.jpg', sitio: 'Wikimedia Commons', autor: 'Macdanpets', licencia: 'CC BY-SA 4.0', categoria: 'canal/desague', descripcion: 'Desague obstruido y de aspecto deteriorado, Nigeria.' },
  { archivo: 'reporte-15-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/2/20/Mathare_River-_Nairobi.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Mathare_River-_Nairobi.jpg', sitio: 'Wikimedia Commons', autor: 'Queen Asali', licencia: 'CC BY-SA 4.0', categoria: 'canal/desague', descripcion: 'Tramo del rio Mathare atravesando un asentamiento informal, agua degradada, Nairobi.' },

  // ---- Reporte 16 (Fernando de la Mora, RIESGO_BAJO) ----
  { archivo: 'reporte-16-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/5/56/FOAMY_PULPING_WASTE_-_NARA_-_552192.jpg', origen: 'https://commons.wikimedia.org/wiki/File:FOAMY_PULPING_WASTE_-_NARA_-_552192.jpg', sitio: 'Wikimedia Commons', autor: 'Doug Wilson (EPA/Documerica, NARA)', licencia: 'Dominio publico', categoria: 'espuma', descripcion: 'Espuma abundante generada por residuo industrial de pulpa de papel (fotografia historica, 1973).' },
  { archivo: 'reporte-16-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/a/aa/Foam.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Foam.jpg', sitio: 'Wikimedia Commons', autor: 'Mercedes Rompani', licencia: 'CC BY-SA 3.0', categoria: 'espuma', descripcion: 'Espuma abundante en superficie de agua, Punta del Este, Uruguay.' },

  // ---- Reporte 17 (Capiatá, RIESGO_BAJO) ----
  { archivo: 'reporte-17-01.webp', url: 'https://images.pexels.com/photos/4406602/pexels-photo-4406602.jpeg?cs=srgb&dl=pexels-eberhardgross-4406602.jpg&fm=jpg', origen: 'https://www.pexels.com/photo/clear-water-flowing-from-pipe-4406602/', sitio: 'Pexels', autor: 'Eberhard Grossgasteiger', licencia: 'Pexels License', categoria: 'agua clara', descripcion: 'Agua clara fluyendo con reflejos desde una tuberia, entorno natural.' },
  { archivo: 'reporte-17-02.webp', url: 'https://images.pexels.com/photos/2249233/pexels-photo-2249233.jpeg?cs=srgb&dl=pexels-theworkof-2249233.jpg&fm=jpg', origen: 'https://www.pexels.com/photo/clear-water-2249233/', sitio: 'Pexels', autor: 'Neil Martin', licencia: 'Pexels License', categoria: 'agua clara', descripcion: 'Salpicadura de agua clara sobre fondo neutro.' },

  // ---- Reporte 18 (Mariano Roque Alonso, RIESGO_BAJO) ----
  { archivo: 'reporte-18-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/1/11/Shopping_vogn.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Shopping_vogn.jpg', sitio: 'Wikimedia Commons', autor: 'gcardinal (Dmitry Valberg)', licencia: 'CC BY 2.0', categoria: 'residuos en cauce', descripcion: 'Carrito de supermercado abandonado dentro del agua, Noruega.' },
  { archivo: 'reporte-18-02.webp', url: 'https://images.pexels.com/photos/15060366/pexels-photo-15060366.jpeg?cs=srgb&dl=pexels-collab-media-173741945-15060366.jpg&fm=jpg', origen: 'https://www.pexels.com/photo/waste-on-a-riverbank-15060366/', sitio: 'Pexels', autor: 'Collab Media', licencia: 'Pexels License', categoria: 'residuos en cauce', descripcion: 'Residuos plasticos y desechos varios en la orilla de un rio.' },

  // ---- Reporte 19 (J. Augusto Saldívar, RIESGO_BAJO) ----
  { archivo: 'reporte-19-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/f/fa/Discharge_pipe.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Discharge_pipe.jpg', sitio: 'Wikimedia Commons', autor: 'USDA', licencia: 'Dominio publico', categoria: 'descarga tuberia', descripcion: 'Tuberia descargando agua hacia un curso de agua.' },
  { archivo: 'reporte-19-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/2/29/DISCHARGE_PIPE_ON_MONTEREY_BAY_BEACH_-_NARA_-_543161.jpg', origen: 'https://commons.wikimedia.org/wiki/File:DISCHARGE_PIPE_ON_MONTEREY_BAY_BEACH_-_NARA_-_543161.jpg', sitio: 'Wikimedia Commons', autor: 'Dick Rowan (EPA/Documerica, NARA)', licencia: 'Dominio publico', categoria: 'descarga tuberia', descripcion: 'Tuberia de descarga hacia la playa, California (1972).' },

  // ---- Reporte 20 (Ypané, RIESGO_BAJO) ----
  { archivo: 'reporte-20-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/Bad_drainage.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Bad_drainage.jpg', sitio: 'Wikimedia Commons', autor: 'Macdanpets', licencia: 'CC BY-SA 4.0', categoria: 'canal/desague', descripcion: 'Desague urbano deficiente con agua de aspecto turbio, Agbara, Nigeria.' },
  { archivo: 'reporte-20-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Lack_of_solid_waste_management_leads_to_blockages_of_the_drainage_%286915329521%29.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Lack_of_solid_waste_management_leads_to_blockages_of_the_drainage_(6915329521).jpg', sitio: 'Wikimedia Commons', autor: 'SuSanA Secretariat', licencia: 'CC BY 2.0', categoria: 'canal/desague', descripcion: 'Drenaje bloqueado por mala gestion de residuos solidos, con agua estancada, Harare.' },

  // ---- Reporte 21 (Asunción centro, SIN_INDICIOS) ----
  { archivo: 'reporte-21-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/a/a2/Glass_of_cold_mineral_water.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Glass_of_cold_mineral_water.jpg', sitio: 'Wikimedia Commons', autor: 'Arria Belli', licencia: 'CC BY-SA 2.0', categoria: 'agua clara en recipiente', descripcion: 'Vaso con agua mineral fria, transparente, servido hasta la mitad.' },
  { archivo: 'reporte-21-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/b/b0/Drinkwater.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Drinkwater.jpg', sitio: 'Wikimedia Commons', autor: 'Adam Smith', licencia: 'CC BY 2.0', categoria: 'agua clara en recipiente', descripcion: 'Vaso lleno de agua potable de aspecto transparente.' },

  // ---- Reporte 22 (San Pablo, SIN_INDICIOS) ----
  { archivo: 'reporte-22-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/1/11/Glass-of-water.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Glass-of-water.jpg', sitio: 'Wikimedia Commons', autor: 'Derek Jensen (Tysto)', licencia: 'Dominio publico', categoria: 'agua clara en recipiente', descripcion: 'Vaso parcialmente lleno de agua clara y transparente.' },
  { archivo: 'reporte-22-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/3/3f/DicWater.jpg', origen: 'https://commons.wikimedia.org/wiki/File:DicWater.jpg', sitio: 'Wikimedia Commons', autor: 'Pakixa', licencia: 'CC BY-SA 4.0', categoria: 'agua clara en recipiente', descripcion: 'Vaso con liquido transparente e incoloro.' },

  // ---- Reporte 23 (Zeballos Cué, SIN_INDICIOS) ----
  { archivo: 'reporte-23-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/b/b5/A_home_well.jpg', origen: 'https://commons.wikimedia.org/wiki/File:A_home_well.jpg', sitio: 'Wikimedia Commons', autor: 'SAMI AZAROUK', licencia: 'CC BY-SA 4.0', categoria: 'pozo limpio', descripcion: 'Pozo residencial en una propiedad privada, entorno cuidado.' },
  { archivo: 'reporte-23-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/4/49/Shallow_hand_dug_well.JPG', origen: 'https://commons.wikimedia.org/wiki/File:Shallow_hand_dug_well.JPG', sitio: 'Wikimedia Commons', autor: 'Carrie Wallestad', licencia: 'CC BY-SA 4.0', categoria: 'pozo limpio', descripcion: 'Extraccion de agua de un pozo poco profundo cavado a mano, Mongolia.' },

  // ---- Reporte 24 (Lambaré, SIN_INDICIOS) ----
  { archivo: 'reporte-24-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/9/98/Glasses_of_water.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Glasses_of_water.jpg', sitio: 'Wikimedia Commons', autor: 'Pohled 111', licencia: 'CC BY-SA 4.0', categoria: 'agua clara en recipiente', descripcion: 'Detalle de vasos con agua clara.' },
  { archivo: 'reporte-24-02.webp', url: 'https://images.unsplash.com/photo-1563733586325-5fb533331826', origen: 'https://unsplash.com/photos/wwsekztDsJI', sitio: 'Unsplash', autor: 'Pratik Gupta', licencia: 'Unsplash License', categoria: 'agua clara en recipiente', descripcion: 'Vaso transparente con agua, enfoque selectivo.' },

  // ---- Reporte 25 (Limpio, SIN_INDICIOS) ----
  { archivo: 'reporte-25-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/A_water_spring_-_Flickr_-_odako1.jpg', origen: 'https://commons.wikimedia.org/wiki/File:A_water_spring_-_Flickr_-_odako1.jpg', sitio: 'Wikimedia Commons', autor: 'Koichi Oda', licencia: 'CC BY-SA 2.0', categoria: 'naciente limpia', descripcion: 'Agua fluyendo de un manantial natural.' },
  { archivo: 'reporte-25-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/e/e7/Gesundheitsbrunnen.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Gesundheitsbrunnen.jpg', sitio: 'Wikimedia Commons', autor: 'Uwe Karl Ullrich', licencia: 'CC BY-SA 4.0', categoria: 'naciente limpia', descripcion: 'Fuente de agua clara en movimiento, fotografia de larga exposicion.' },

  // ---- Reporte 26 (Areguá, SIN_INDICIOS) ----
  { archivo: 'reporte-26-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/e/e8/A_small_river_sparkling.jpg', origen: 'https://commons.wikimedia.org/wiki/File:A_small_river_sparkling.jpg', sitio: 'Wikimedia Commons', autor: 'Nabin845', licencia: 'CC BY-SA 4.0', categoria: 'arroyo limpio', descripcion: 'Pequeno rio de aspecto brillante y limpio, Nepal.' },
  { archivo: 'reporte-26-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/7/78/Aguas_blancas.JPG', origen: 'https://commons.wikimedia.org/wiki/File:Aguas_blancas.JPG', sitio: 'Wikimedia Commons', autor: 'Alejandro1000', licencia: 'CC BY-SA 3.0', categoria: 'arroyo limpio', descripcion: 'Arroyo de aguas claras y rapidas.' },

  // ---- Reporte 27 (Ypacaraí, SIN_INDICIOS) ----
  { archivo: 'reporte-27-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/6/61/African_stream_jpg.jpg', origen: 'https://commons.wikimedia.org/wiki/File:African_stream_jpg.jpg', sitio: 'Wikimedia Commons', autor: 'Juliegwen', licencia: 'CC BY-SA 4.0', categoria: 'arroyo limpio', descripcion: 'Arroyo rodeado de vegetacion, Nigeria.' },
  { archivo: 'reporte-27-02.webp', url: 'https://images.unsplash.com/photo-1773563633072-050d63ebcd45', origen: 'https://unsplash.com/photos/a-clear-river-flows-through-a-lush-green-forest-ZxHbi4w4b38', sitio: 'Unsplash', autor: 'Marijan Sivric', licencia: 'Unsplash License', categoria: 'arroyo limpio', descripcion: 'Rio de aspecto claro atravesando un bosque denso.' },

  // ---- Reporte 28 (Itá, SIN_INDICIOS) ----
  { archivo: 'reporte-28-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Balmblae_Burn_Falkland.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Balmblae_Burn_Falkland.jpg', sitio: 'Wikimedia Commons', autor: 'Patjos.scot', licencia: 'CC0 1.0', categoria: 'arroyo limpio', descripcion: 'Arroyo de aspecto limpio junto a un edificio historico, Escocia.' },
  { archivo: 'reporte-28-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Akagwo_stream.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Akagwo_stream.jpg', sitio: 'Wikimedia Commons', autor: 'AfricanLibrarian', licencia: 'CC BY-SA 4.0', categoria: 'arroyo limpio', descripcion: 'Arroyo que riega tierras de cultivo, Nigeria.' },

  // ---- Reporte 29 (Yaguarón, SIN_INDICIOS) ----
  { archivo: 'reporte-29-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/d/d7/Bach_mit_Blumen.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Bach_mit_Blumen.jpg', sitio: 'Wikimedia Commons', autor: 'ConstantinRGW', licencia: 'CC BY-SA 4.0', categoria: 'arroyo limpio', descripcion: 'Arroyo de agua clara con flores en la orilla.' },
  { archivo: 'reporte-29-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Sarek_Skierffe_Rapadelta.jpg', origen: 'https://commons.wikimedia.org/wiki/File:Sarek_Skierffe_Rapadelta.jpg', sitio: 'Wikimedia Commons', autor: 'Mg-k', licencia: 'CC BY-SA 3.0', categoria: 'arroyo limpio', descripcion: 'Delta de un rio glacial de aspecto limpio, Parque Nacional Sarek, Suecia.' },

  // ---- Reporte 30 (Pirayú, SIN_INDICIOS) ----
  { archivo: 'reporte-30-01.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/e/ec/Uncovered_water_canal_in_Irh%C3%A1s-%C3%A1rok._-_Csilleb%C3%A9rc%2C_Budapest.JPG', origen: 'https://commons.wikimedia.org/wiki/File:Uncovered_water_canal_in_Irhás-árok._-_Csillebérc,_Budapest.JPG', sitio: 'Wikimedia Commons', autor: 'Globetrotter19', licencia: 'CC BY-SA 3.0', categoria: 'canal limpio', descripcion: 'Canal de agua abierto y de aspecto limpio, Budapest.' },
  { archivo: 'reporte-30-02.webp', url: 'https://upload.wikimedia.org/wikipedia/commons/4/45/Covered_water_canal_in_Irh%C3%A1s-%C3%A1rok._-_Csilleb%C3%A9rc%2C_Budapest.JPG', origen: 'https://commons.wikimedia.org/wiki/File:Covered_water_canal_in_Irhás-árok._-_Csillebérc,_Budapest.JPG', sitio: 'Wikimedia Commons', autor: 'Globetrotter19', licencia: 'CC BY-SA 3.0', categoria: 'canal limpio', descripcion: 'Tramo cubierto del mismo sistema de canal, Budapest.' },
].map((img) => ({ ...img, fechaConsulta: FECHA_CONSULTA }));

module.exports = { IMAGENES };
